# datadog-php-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-datadog-ini
  namespace: nextcloud
data:
  datadog.ini: |
    [datadog]
    datadog.trace.enabled = On
    datadog.trace.cli_enabled = On
    datadog.service = nextcloud
    datadog.env = prod
    datadog.version = 33.0.8
    datadog.trace.agent_url = unix:///var/run/datadog/apm.socket
    datadog.dogstatsd_url = unix:///var/run/datadog/dsd.socket
    datadog.trace.sidecar_trace_sender = Off
    datadog.trace.auto_flush_enabled = On
    datadog.trace.generate_root_span = On
    datadog.trace.force_flush_on_shutdown = On
