image:
  repository: nextcloud
  tag: "33.0.8-fpm"
  pullPolicy: IfNotPresent
  flavor: "fpm"

nginx:
  enabled: true
  image:
    repository: nginx
    tag: "alpine"
    pullPolicy: IfNotPresent
  config:
    default: true

host: "nextcloud.fareed.in"

storage:
  className: "nfs-client-retain"
  data:
    size: 1000Gi
  db:
    className: "nfs-fast-retain"
    size: 5Gi

extraEnv: []
extraVolumes: []
extraVolumeMounts: []

mariadb:
  image:
    repository: mariadb
    tag: "12.3"
  database: "nextcloud"
  user: "nextcloud"
  auth:
    password: "changeme_nextcloud_db_password"
    rootPassword: "changeme_mariadb_root_password"

redis:
  image:
    repository: redis
    tag: "8.10.0-alpine3.23"
  auth:
    enabled: true
    password: "changeme_redis_password"

secrets:
  mysqlRootPassword: "changeme_mariadb_root_password"
  mysqlPassword: "changeme_nextcloud_db_password"

dbBackup:
  enabled: true
  schedule: "0 3 * * 0"
  retentionDays: 30
  storageClass: "nfs-client-retain"
  size: 5Gi
