apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: {{ .Release.Name }}-mariadb
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          args:
            - "--transaction-isolation=READ-COMMITTED"
            - "--binlog-format=ROW"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secrets
                  key: MYSQL_USER
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: mariadb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.storage.db.className | quote }}
        resources:
          requests:
            storage: {{ .Values.storage.db.size | default "5Gi" }}
