apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.data.size }}
