apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | quote }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | quote }}
  MYSQL_DATABASE: {{ .Values.mariadb.database | quote }}
  MYSQL_USER: {{ .Values.mariadb.user | quote }}
